//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BubbleTea.WinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryList
    {
        public CountryList()
        {
            this.Customers = new HashSet<Customers>();
        }
    
        public string CountryCode { get; set; }
        public string CountryName { get; set; }
    
        public virtual ICollection<Customers> Customers { get; set; }
    }
}
